# mostly taken from github.com/robustirc/bridge
sudo: false

language: go

script:
  # Check whether files are syntactically correct.
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  # Check whether files were not gofmt'ed.
  - "gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)"
  # Run go vet for further checking.
  - go vet github.com/pseyfert/go-dayvider
  # Run tests (output validation)
  - go test github.com/pseyfert/go-dayvider -bookings 1 -repetitions 5
  - go test github.com/pseyfert/go-dayvider -bookings 2 -repetitions 10
  - go test github.com/pseyfert/go-dayvider -bookings 3 -repetitions 10
  - go test github.com/pseyfert/go-dayvider -bookings 4 -repetitions 10
  - go test github.com/pseyfert/go-dayvider -bookings 5 -repetitions 500
  - go test github.com/pseyfert/go-dayvider -bookings 10 -repetitions 500
  - go test github.com/pseyfert/go-dayvider -bookings 100 -repetitions 100
  - go test github.com/pseyfert/go-dayvider -bookings 1000 -repetitions 20
  - go test -coverprofile=cover.out -repetitions 500 -bookings 300 -days 2 && go tool cover -html=cover.out -o cover.html
